#############################################################################
# NOTICE                                                                    #
#                                                                           #
# This software (or technical data) was produced for the U.S. Government    #
# under contract, and is subject to the Rights in Data-General Clause       #
# 52.227-14, Alt. IV (DEC 2007).                                            #
#                                                                           #
# Copyright 2016 The MITRE Corporation. All Rights Reserved.                #
#############################################################################

#############################################################################
# Copyright 2016 The MITRE Corporation                                      #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#    http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################
---
- name: Install JDK
  yum: name=jdk1.8.0_60 state=latest disablerepo=* enablerepo=mpf-repo

- name: Install JRE
  yum: name=jre1.8.0_60 state=latest disablerepo=* enablerepo=mpf-repo

#Configure alternatives to point at latest java
- name: Setup alternatives for java
  alternatives: name=java link=/usr/bin/java path=/usr/java/latest/jre/bin/java
- name: Setup alternatives for javac
  alternatives: name=javac link=/usr/bin/javac path=/usr/java/latest/bin/javac
- name: Setup alternatives for jar
  alternatives: name=jar link=/usr/bin/jar path=/usr/java/latest/bin/jar
