#############################################################################
# NOTICE                                                                    #
#                                                                           #
# This software (or technical data) was produced for the U.S. Government    #
# under contract, and is subject to the Rights in Data-General Clause       #
# 52.227-14, Alt. IV (DEC 2007).                                            #
#                                                                           #
# Copyright 2018 The MITRE Corporation. All Rights Reserved.                #
#############################################################################

#############################################################################
# Copyright 2018 The MITRE Corporation                                      #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#    http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################
---
#file: update-all-mpf-nodes.yml

# Example usage:
# ansible-playbook <path>/update-all-mpf-nodes.yml --ask-pass --user $USER_NAME --become --ask-become-pass --extra-vars all_mpf_nodes="hostA.somedomain[7800],hostB.somedomain[7800],"

# DEBUG
# ansible-playbook /home/mpf/git/openmpf-projects/openmpf/trunk/ansible/install/ansible/update-all-mpf-nodes.yml --user $USER_NAME -e master_host "{{ hostvars[groups['mpf-master'][0]]['inventory_hostname'] }}" -e all_mpf_nodes="hostA.somedomain[7800],hostB.somedomain[7800],"

- hosts: all

  vars:
    - mpf_home: "{{ lookup('env','MPF_HOME') | default('/opt/mpf', true) }}"
    - deployment_config: "{{ lookup('file', '{{ mpf_home }}/share/deployment_config.json') | from_json }}"

  pre_tasks:
    - name: Set workflow manager REST endpoint to update ALL_MPF_NODES
      set_fact:
        can_update_nodes: "{% if deployment_config.https.install and keystore_filest.stat.exists == False %}False{% else %}True{% endif %}"
        update_nodes_uri: "{% if deployment_config.https.install %}https://{{ master_host }}:8443/workflow-manager/rest/env/update?allMpfNodes={% else %}http://{{ master_host }}:8080/workflow-manager/rest/env/update?allMpfNodes={% endif %}"

  post_tasks:
    - name: "Update workflow manager ALL_MPF_NODES"
      uri:
        url: "{{ update_nodes_uri }}{{ all_mpf_nodes }}"
        method: GET
        follow_redirects: all
        force_basic_auth: yes
        user: "admin"
        password: "{{ admin_wfm_pw }}"
        status_code: 200
        return_content: yes
        timeout: 150
        validate_certs: no
      environment:
        no_proxy: "{{ master_host }}"
      when: can_update_nodes
      register: update_results
      failed_when: update_results.status == 404