#############################################################################
# NOTICE                                                                    #
#                                                                           #
# This software (or technical data) was produced for the U.S. Government    #
# under contract, and is subject to the Rights in Data-General Clause       #
# 52.227-14, Alt. IV (DEC 2007).                                            #
#                                                                           #
# Copyright 2019 The MITRE Corporation. All Rights Reserved.                #
#############################################################################

#############################################################################
# Copyright 2019 The MITRE Corporation                                      #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#    http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################
---
#file: roles/repo/tasks/apr.yml
#TODO: The apr installs shouldn't be needed, but must take precedence over mpf-extraction's version.
- name: Install apr
  yum:
    name=apr
    state=present
    update_cache=yes
    disablerepo=*
    enablerepo=mpf-local-repo

- name: Install apr-util
  yum:
    name=apr-util
    state=present
    update_cache=yes
    disablerepo=*
    enablerepo=mpf-local-repo

- name: Install apr-util-ldap
  yum:
    name=apr-util-ldap
    state=present
    update_cache=yes
    disablerepo=*
    enablerepo=mpf-local-repo
