#############################################################################
# NOTICE                                                                    #
#                                                                           #
# This software (or technical data) was produced for the U.S. Government    #
# under contract, and is subject to the Rights in Data-General Clause       #
# 52.227-14, Alt. IV (DEC 2007).                                            #
#                                                                           #
# Copyright 2019 The MITRE Corporation. All Rights Reserved.                #
#############################################################################

#############################################################################
# Copyright 2019 The MITRE Corporation                                      #
#                                                                           #
# Licensed under the Apache License, Version 2.0 (the "License");           #
# you may not use this file except in compliance with the License.          #
# You may obtain a copy of the License at                                   #
#                                                                           #
#    http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                           #
# Unless required by applicable law or agreed to in writing, software       #
# distributed under the License is distributed on an "AS IS" BASIS,         #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
# See the License for the specific language governing permissions and       #
# limitations under the License.                                            #
#############################################################################
---
#file: roles/repo/tasks/main.yml
- name: Setup ssh-key
  include: ssh-key.yml

- name: Disable SE Linux
  selinux: state=disabled

- name: Create MPF Repo
  command: createrepo {{ repo_directory }}/rpms

- name: Config yum to utilize MPF local repository
  template: src=mpf-local.repo.j2 dest=/etc/yum.repos.d/mpf-local.repo

- name: Config yum to utilize MPF repository
  template: src=mpf.repo.j2 dest=/etc/yum.repos.d/mpf.repo

- name: Upgrade openssh
  yum:
    name=openssh
    state=latest
    update_cache=yes
    disablerepo=*
    enablerepo=mpf-local-repo

- name: Install APR libs
  include: apr.yml

- name: Install httpd
  include: httpd.yml
